/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.mw.devschool.wordcount;

import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.ArgumentMatchers;
import org.mockito.Mockito;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.URISyntaxException;
import java.nio.file.Path;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class AppTest {

    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App(System.out, new BufferedReader(new InputStreamReader(System.in)), null);
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testAppIsRequestingInputNicely() throws IOException {
        // GIVEN
        final PrintStream outputSpy = Mockito.spy(System.out);
        BufferedReader reader = mock(BufferedReader.class);
        App underTest = new App(outputSpy, reader, new WordCounter());

        when(reader.readLine()).thenReturn("Mary had a little lamb");

        // WHEN
        final String aResult = underTest.readInputFromCli();

        // THEN
        assertThat(aResult, is("Mary had a little lamb"));
        Mockito.verify(outputSpy).print(ArgumentMatchers.argThat((String s) -> s.trim().equals("Enter text:")));
        Mockito.verify(reader).readLine();
    }


    @Test
    public void testAppPrintsWordCountCorrectly() {
        // GIVEN
        final PrintStream outputSpy = Mockito.spy(System.out);
        BufferedReader reader = mock(BufferedReader.class);
        App underTest = new App(outputSpy, reader, new WordCounter());

        // WHEN
        underTest.printWordCount(5);

        // THEN
        verify(outputSpy).println(eq("The word count is: 5"));
    }

    @Test
    public void testReadFileContent() throws URISyntaxException, IOException {
        //GIVEN
        final PrintStream outputSpy = Mockito.spy(System.out);
        App underTest = new App(outputSpy, null, new WordCounter());
        Path testFile = Path.of(getClass().getResource("test.txt").toURI());

        //WHEN
        String fileContent = underTest.readInputFromFile(testFile.toAbsolutePath().toString());

        //THEN
        verify(outputSpy).printf("Reading input from file '%s'%n", testFile.toAbsolutePath());
        assertEquals("Das ist ein Test!", fileContent);
    }

    @Test
    public void integrationTest_ASSERT_THAT_word_count_is_calculated_and_printed_correctly_WHEN_input_differs_from_examples() throws IOException {
        // GIVEN
        final PrintStream outputSpy = Mockito.spy(System.out);
        BufferedReader reader = mock(BufferedReader.class);
        App underTest = new App(outputSpy, reader, new WordCounter());
        when(reader.readLine()).thenReturn("This is an unexpected test sentence; it might really throw you off.");
        final int expectedNumberOfWords = 12;

        // WHEN
        underTest.run(null);

        // THEN
        verify(reader).readLine();
        ArgumentCaptor<String> outputArgCaptor = ArgumentCaptor.forClass(String.class);
        verify(outputSpy).println(outputArgCaptor.capture());
        assertTrue(outputArgCaptor.getValue().endsWith(" " + expectedNumberOfWords));
    }

    @Test
    public void integrationTest_ASSERT_THAT_word_count_is_calculated_and_printed_correctly_WHEN_input_file_is_passed() throws URISyntaxException {
        // GIVEN
        final PrintStream outputSpy = Mockito.spy(System.out);
        App underTest = new App(outputSpy, null, new WordCounter());
        final int expectedNumberOfWords = 4;

        Path testFile = Path.of(getClass().getResource("test.txt").toURI());
        // WHEN
        underTest.run(testFile.toAbsolutePath().toString());

        // THEN
        ArgumentCaptor<String> outputArgCaptor = ArgumentCaptor.forClass(String.class);
        verify(outputSpy).println(outputArgCaptor.capture());
        assertTrue(outputArgCaptor.getValue().endsWith(" " + expectedNumberOfWords));
    }
}
