/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.mw.devschool.wordcount;

import java.io.*;

public class App {
    private final BufferedReader inputStream;
    private final PrintStream outputStream;

    public App(PrintStream outputStream, BufferedReader inputStream) {
        this.inputStream = inputStream;
        this.outputStream = outputStream;
    }

    public static void main(String[] args) {
        final App app = new App(System.out, new BufferedReader(new InputStreamReader(System.in)));
        System.out.println(app.getGreeting());

        app.run();
    }

    public String getGreeting() {
        return "Hello world.";
    }



    void run() {
        String input = "";
        try {
            input = readInput();
        } catch (IOException e) {
            outputStream.println("Failed to read input.");
            e.printStackTrace();
            System.exit(-1);
        }

        int wordCount = countWords(input);

        printWordCount(wordCount);
    }



    String readInput() throws IOException {
        outputStream.print("Enter text: ");
        return inputStream.readLine();
    }


    int countWords(String text) {
        return text.split(" ").length;
    }


    void printWordCount(int wordCount) {
        outputStream.println("The word count is: " + wordCount);
    }
}
